# This is a basic workflow to help you get started with Actions

name: Relase_version

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-node:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: node:14
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      run: node --version
      run: npm --version
      uses: actions/checkout@v3
      run: npm install
